version: "3.9"
services:
  app:
    build: .
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
    # nginx.conf belemappelem mentsuk /etc/nginx/nginx.conf:ro" ide
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
